#!/usr/bin/env bash

# Install nginx on web server; Nginx should be listening on port 80
# Install nginx

apt-get update
apt-get -y install nginx

# Configure nginx
echo "Hello World!" > /var/www/html/index.html

# Restart nginx
/usr/sbin/service nginx restart

